apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustopytime
  namespace: projects
spec:
  selector:
    matchLabels:
      app: pypy
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pypy
    spec:
      containers:
      - name: livetime
        image: coleworld1111/inspired:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000