apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustopytime
  namespace: projects
spec:
  selector:
    matchLabels:
      app: pypy
  replicas: 4
  template:
    metadata:
      labels:
        app: pypy
  
